site_name: Artificial Primary Care Data 
nav:
  - Home: index.md
  - Generating Data: users.md
  - Developer Information: 
    - devs/dev.md
    - Resources: devs/resources.md
    - Java: devs/java.md
  - UK Adaptations: ukadaptions.md
  - Example Outputs: outputs.md
  - Hypertension Dataset: hypertensiondataset.md
  
theme: 
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - tables
  - footnotes
  - attr_list